language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x ./gradlew
script:
- "./gradlew --no-daemon check"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload --debug"
  on:
    tags: true
env:
  global:
  - secure: C5wNbVb2ik6GxhUG9zFJ19rR1pdV4iRFeaazppVSfb4J1A3PE28PwhN+OB4xx5xemYwrOpwgqvunDWNoX/CRY+SEB1tFTbOzBOL+Cjrkh6NpDXtK1fijxYu3JjE+1fjJIIO07Yrrsrj4g8cbW1LFv8t0uTgLnPgTiQAtcbvZr1Rb2RJfnqUjU3vMswbxvJud37IrP50rAILqCtvAKK+XsGTDoDbryxQxHkMg3pZWu/1kCf5mfnpcyBkWN4b/0Y5coOB1eHlzrYVAY9pmxx9Q5Ww9EPZaXx6mut0p8UAHvVVZli4lgWtMpeJ06Q/VQ9YpCeBFzf+cbbMOLZ+oMFoSutrAYd48AYfrj4M8+P4m7UtzOWW7YeA7QfxG7A7V0jU4b8S7jiDFVQa4awzNpVf7LrajIpDafRl+8hgcCKqQgsl0RDE5hfLsBFQfwtcM4pL+aqM7mCdc+UIygyCNzZ0ogAWiACu+cR3+J8Dml2H/fb7/Wiu+pkWSPi1DlifKuCR0UY+mIbnWBu4OMeu4s00o6JO5k20wGKkObDtrVlBzbRB/JSIknlVsHXHe+7QOuGVT9Bh03uHyCbGhW6wzv1RXOAkB1M44J+lrE9hB1R1LajlKzo7gKJVdzk8UWylJgr+d+jG8WiF+lCPezzQSqt7APY7RHl4iC4AfIlYamseoJjc=
  - secure: KR8PVCUuQktr4Ke76vqgoI8kA4tnYl0T6dXzlIDEccxFijERaAPKmqUGutfFl7nH9nq3vAJgcp/JEKOv3I2pqhuue0gyo+65tTXGxwWFpckvDkYSR10IQBWYt9LPAIMauOvIbJvJc58lZ8XXK77n3wkdBWyFv+m3cYxzMuHL9mooFx7fMyxm6oefSPp7Lab+P2eXp23O66mOxguA6x2xAbwt510pcmPCXzkxlhqzJa8EeRYTJCX2Y6mFkEdZtnMZiy+n9b3EowWfMYec7/OAbtFL+OOiA33nhKMmWCSB/aQ1BfEG6+43KO9554CWMkYX68/foIYFe7ndw9Dmwp6BVq1vid3mqzVmcY0vcQOrH6rX7uFCjW3ZUEHMZ9QeqfwjV8piK1qqdu+so5xq+8kcDzlpvVOjL3TNTK7PcAC3h7LKuOXaZOtJTRMY7i68B5PEXiSd3KlsbfgxZUZ4idyG7h4afSCKD7bwxDJD7ibpCl8dmAmWiW5er/vW9y5r5D1sWh9xtfqqaSM5RMlnry4GjbUeVn6ZMUfTEE0HUitYJM8duTU8TvT4bLIlOuVPfrcYcFtl5XAdUIayy8RuDIVVehPa7NE6clJ2qt959FdmWZ49o5TWWuVCrGNHs28PPqPJMo0iIK5dJxm0zHzzLGE771Jkg2ltet0LgoW8gaG/pJY=
